language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - npm install

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - npm run build
  - docker --version # print the version for logging
  - docker build -t udagram-api-users .
  - docker tag udagram-api-users scharati/udagram-api-users:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push scharati/udagram-api-users

